name: convenient_way_sender
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.1.0
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  logging: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.1.1
  dotenv: ^4.0.1
  jwt_decode: ^0.3.1
  firebase_auth: ^4.3.0
  get_cli: ^0.2.30
  flutter_dotenv: ^5.0.2
  gap: ^2.0.0
  geolocator: ^9.0.2
  flutter_map: ^3.0.0
  fluentui_icons: ^1.0.0
  uuid: ^3.0.6
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  google_fonts: ^3.0.1
  flutter_multi_select_items: ^0.4.2
  pull_to_refresh: ^2.0.0
  signalr_netcore: ^1.3.3
  flutter_chat_ui: ^1.6.4
  flutter_chat_types: ^3.4.5
  file_picker: ^5.2.3
  image_picker: ^0.8.6+1
  bubble: ^1.2.1
  http: ^0.13.5
  latlong2: ^0.8.1
  quickalert: ^1.0.1
  permission_handler: ^10.2.0
  material_dialogs: ^1.1.3
  motion_toast: ^2.6.4
  flutter_format_money_vietnam: ^0.0.2
  animated_splash_screen: ^1.3.0
  page_transition: "^2.0.9"
  flutter_native_splash: ^2.2.16
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.10
  firebase_core_platform_interface: ^4.5.2
  lottie: ^2.2.0
  currency_text_input_formatter: ^2.1.8
  shimmer: ^2.0.0
  get_ip_address: ^0.0.5
  webview_flutter: ^4.0.2
  intl: ^0.17.0
  antdesign_icons: ^0.0.3
  flutter_svg_provider: ^1.0.3
  fluttericon: ^2.0.0
  scroll_navigation: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_map_location_marker: ^5.2.1
  sliding_up_panel: ^2.0.0+1
  card_loading: ^0.2.2
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.1
  flutter_typeahead: ^3.2.7
  flutter_login: ^4.1.1
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  expandable: ^5.0.1
  elegant_notification: ^1.7.0
  loader_overlay: ^2.1.0
  cupertino_stepper: ^0.2.1
  barcode: ^2.2.3
  just_the_tooltip: ^0.0.12
  enhance_stepper: ^0.1.1
  flutter_barcode_scanner: ^2.0.0
  multi_image_picker_view: ^0.0.14
  get_storage: ^2.1.1
  positioned_tap_detector_2: ^1.0.4
  restart_app: ^1.1.2
  flutter_switch: ^0.3.2
  flutter:
    sdk: flutter
  syncfusion_flutter_datepicker: ^20.4.54
  time_range: ^1.1.0
  time_range_picker: ^2.2.0
  day_night_time_picker: ^1.2.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/gifs/
    - assets/lottiefiles/
    - assets/sounds/
    - .env
