// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXy653QraMBHtNQcsRTn3Ac9V6xqj_SsQ',
    appId: '1:465111730158:android:3193ab43211679f237b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    storageBucket: 'convenient-way.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWgBJ_4hWesEzmuzPt9h5-b6epxng4jY',
    appId: '1:465111730158:ios:e9bcf80581495a8437b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    storageBucket: 'convenient-way.appspot.com',
    androidClientId: '465111730158-bf8huljh29cfcsn3ffq3ftvfre5fdqel.apps.googleusercontent.com',
    iosClientId: '465111730158-8j8emhcbhvq5rhfcsai4tbopgf1vhqc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.convenientWaySender',
  );
}
